apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: k8s-nodejs-api:latest
        imagePullPolicy: Never
        name: api
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80 
          name: api
