apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 80
  selector:
    app: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - 
          name: DB_HOST 
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets 
              key: DB_HOST 
        - 
          name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets 
              key: DB_USER 
        - 
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets 
              key: DB_PASSWORD 
        - 
          name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets 
              key: DB_NAME 
        ports:
        - containerPort: {{ .Values.app.port }}
          name: {{ .Release.Name }}
