apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets 
type: Opaque
data:
  DB_HOST: "bXlzcWw="
  DB_USER: "cm9vdA=="
  DB_PASSWORD: "cGFzc3dvcmQ="
  DB_NAME: "bm9kZWpzX2V4YW1wbGU="
