apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: k8s-nodejs-api:latest
        imagePullPolicy: Never
        name: api
        env:
        - name: PORT
          value: "80"
        - 
          name: DB_HOST 
          valueFrom:
            secretKeyRef:
              name: api-secrets 
              key: DB_HOST 
        - 
          name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: api-secrets 
              key: DB_USER 
        - 
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets 
              key: DB_PASSWORD 
        - 
          name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: api-secrets 
              key: DB_NAME 
        ports:
        - containerPort: 80 
          name: api
